import { getAnthropicClient } from "../lib/anthropicClient.js";
import { getSupabaseClient } from "../lib/supabaseClient.js";
import { getActivePrompt, interpolateTemplate } from "./agentPrompts.js";
import { getBookFacts, formatBookFactsSection } from "./bookFacts.js";
import { listCodexEntries } from "./bookContextTools.js";
import type Anthropic from "@anthropic-ai/sdk";
import type { EffortLevel, ExtractedEntityCandidate, PlanningChatMessage, PlanningRun, PlanningStage } from "../types/domain.js";

// The Webnovel Planning Engine: Stage 1 Core Summary -> Stage 2 Act
// Outlines -> Stage 3 Chapter Beats, each stage generated by Claude
// ("Generator" here means planning text — summaries/outlines/beats, NEVER
// manuscript prose, which stays exclusively Hanami's job via the existing
// /generate-prose and MCP tools), critiqued by two parallel critics,
// synthesized by an Arbitrator, and gated on human approval before
// advancing. Every agent's behavior is entirely prompt-driven — every
// system_prompt/user_prompt_template is authored by the writer via the
// Prompt Editor (src/services/agentPrompts.ts) and stored in
// agent_prompts; this file only supplies the mechanics that make those
// prompts actually run reliably (the loop, the interpolation, structured
// JSON verification with a retry, and where each artifact/context slot
// comes from) — it contains no prompt content of its own.

const STAGE_ORDER: Exclude<PlanningStage, "all">[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats"];

function nextStage(stage: PlanningStage): Exclude<PlanningStage, "all"> | null {
  const index = STAGE_ORDER.indexOf(stage as Exclude<PlanningStage, "all">);
  if (index === -1 || index === STAGE_ORDER.length - 1) return null;
  return STAGE_ORDER[index + 1] ?? null;
}

async function loadRun(runId: string): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from("planning_runs").select("*").eq("id", runId).maybeSingle();
  if (error) throw new Error(`Failed to load planning run: ${error.message}`);
  if (!data) throw new Error(`No planning run found with id ${runId}.`);
  return data as PlanningRun;
}

async function saveRun(runId: string, patch: Record<string, unknown>): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", runId)
    .select("*")
    .single();
  if (error) throw new Error(`Failed to update planning run: ${error.message}`);
  return data as PlanningRun;
}

// Marks the run failed with a clear message rather than leaving it stuck
// in an intermediate status with no explanation — the one thing worse
// than a failed pipeline step is a silent one.
async function markFailed(runId: string, error: unknown): Promise<never> {
  const message = error instanceof Error ? error.message : String(error);
  await saveRun(runId, { status: "failed", last_error: message });
  throw error instanceof Error ? error : new Error(message);
}

async function callAgent(params: { systemPrompt: string; userMessage: string; model: string; effort: EffortLevel; maxTokens?: number }): Promise<string> {
  const anthropic = getAnthropicClient();
  const response = await anthropic.messages.create({
    model: params.model,
    max_tokens: params.maxTokens ?? 8000,
    system: params.systemPrompt,
    thinking: { type: "adaptive" },
    output_config: { effort: params.effort },
    messages: [{ role: "user", content: params.userMessage }],
  });

  return response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();
}

function tryParseJson(text: string): unknown | undefined {
  const stripped = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "")
    .trim();
  try {
    return JSON.parse(stripped);
  } catch {
    const match = stripped.match(/[[{][\s\S]*[\]}]/);
    if (!match) return undefined;
    try {
      return JSON.parse(match[0]);
    } catch {
      return undefined;
    }
  }
}

// Verify, don't just trust the instruction — same principle Ghost Editor
// already established for banned terms in this project. A critic/
// arbitrator prompt asks for JSON; this checks the response actually is
// valid JSON and gives the model exactly one corrective retry before
// surfacing a real failure, rather than silently storing garbage or
// silently accepting prose instead of the requested structure.
async function callAgentForJson(params: { systemPrompt: string; userMessage: string; model: string; effort: EffortLevel }): Promise<unknown> {
  const first = await callAgent(params);
  const parsedFirst = tryParseJson(first);
  if (parsedFirst !== undefined) return parsedFirst;

  const retryMessage = `${params.userMessage}\n\nYour previous response was not valid JSON. Return ONLY a single valid JSON object or array — no surrounding prose, no markdown code fences.`;
  const second = await callAgent({ ...params, userMessage: retryMessage });
  const parsedSecond = tryParseJson(second);
  if (parsedSecond !== undefined) return parsedSecond;

  throw new Error("Agent did not return valid JSON after one corrective retry.");
}

async function buildBookContext(bookId: string): Promise<string> {
  const [facts, codexEntries] = await Promise.all([getBookFacts(bookId), listCodexEntries(bookId)]);
  return [formatBookFactsSection(facts), "", "## Codex Entries", "", JSON.stringify(codexEntries, null, 2)].join("\n");
}

export async function createPlanningRun(params: { bookId: string; userId: string }): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .insert({ book_id: params.bookId, user_id: params.userId })
    .select("*")
    .single();
  if (error) throw new Error(`Failed to create planning run: ${error.message}`);
  return data as PlanningRun;
}

export async function getPlanningRun(runId: string): Promise<PlanningRun> {
  return loadRun(runId);
}

// Runs the Generator for the run's current_stage. Sees the book's existing
// Codex/facts (so continuing an already-written book stays consistent with
// what's already on the page), the prior stage's approved artifact for
// continuity, and — if this generation follows a rejection — the
// Arbitrator's compiled delta directive telling it exactly what to change.
export async function generateStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "generator", run.current_stage);
    const bookContext = await buildBookContext(run.book_id);

    const stageIndex = STAGE_ORDER.indexOf(run.current_stage as Exclude<PlanningStage, "all">);
    const priorStage = stageIndex > 0 ? STAGE_ORDER[stageIndex - 1] : null;
    const priorArtifact = priorStage ? (run.stage_artifacts[priorStage] ?? "") : "";

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      BOOK_CONTEXT: bookContext,
      PRIOR_STAGE_ARTIFACT: priorArtifact,
      FINAL_DELTA_DIRECTIVE: run.final_delta_directive ?? "",
    });

    // Stage 3 (Beats) has to come back as parseable JSON — it's the one
    // stage whose approved output gets materialized into real
    // chapter_beats rows (see materializeBeats), which needs real
    // structure to insert, not prose a human would read and a machine
    // can't reliably split into chapters/beats. Stage 1/2 stay plain text
    // — a summary and act outline are meant to be read, not parsed.
    const artifact =
      run.current_stage === "stage_3_beats"
        ? JSON.stringify(
            await callAgentForJson({ systemPrompt: prompt.system_prompt, userMessage, model: prompt.model, effort: prompt.effort })
          )
        : await callAgent({ systemPrompt: prompt.system_prompt, userMessage, model: prompt.model, effort: prompt.effort });

    return saveRun(runId, {
      status: "critiquing",
      stage_artifacts: { ...run.stage_artifacts, [run.current_stage]: artifact },
      // Consumed once regeneration happens — doesn't linger and silently
      // apply to a later, unrelated regeneration of this stage.
      final_delta_directive: null,
    });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Fires the Logic and Suspense critics in parallel — one bounded request,
// not a chain — against the stage artifact that was just generated.
export async function runCritique(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const artifact = run.stage_artifacts[run.current_stage as Exclude<PlanningStage, "all">] ?? "";
    const bookContext = await buildBookContext(run.book_id);

    const [logicPrompt, suspensePrompt] = await Promise.all([
      getActivePrompt(run.book_id, "logic_critic", run.current_stage),
      getActivePrompt(run.book_id, "suspense_critic", run.current_stage),
    ]);

    const [logicReview, suspenseReview] = await Promise.all([
      callAgentForJson({
        systemPrompt: logicPrompt.system_prompt,
        userMessage: interpolateTemplate(logicPrompt.user_prompt_template, { BOOK_CONTEXT: bookContext, CURRENT_ARTIFACT: artifact }),
        model: logicPrompt.model,
        effort: logicPrompt.effort,
      }),
      callAgentForJson({
        systemPrompt: suspensePrompt.system_prompt,
        userMessage: interpolateTemplate(suspensePrompt.user_prompt_template, { BOOK_CONTEXT: bookContext, CURRENT_ARTIFACT: artifact }),
        model: suspensePrompt.model,
        effort: suspensePrompt.effort,
      }),
    ]);

    return saveRun(runId, {
      status: "awaiting_arbitration",
      panel_reviews: { logic_critic: logicReview, suspense_critic: suspenseReview },
    });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Arbitrator's panel-synthesis pass: compiles both critiques into whatever
// form the writer's own prompt asks for, then opens the human review gate.
export async function runArbitration(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const artifact = run.stage_artifacts[run.current_stage as Exclude<PlanningStage, "all">] ?? "";
    const prompt = await getActivePrompt(run.book_id, "arbitrator_panel", run.current_stage);

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      CURRENT_ARTIFACT: artifact,
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
    });

    const synthesis = await callAgentForJson({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    return saveRun(runId, { status: "awaiting_user_review", arbitrator_synthesis: synthesis });
  } catch (error) {
    return markFailed(runId, error);
  }
}

interface ParsedBeatsArtifact {
  chapters: { chapterNumber: number; title?: string; beats: { title: string; outlineText: string }[] }[];
}

function parseBeatsArtifact(raw: string): ParsedBeatsArtifact {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Stage 3 artifact is not valid JSON — cannot materialize beats into the Outliner.");
  }
  const chapters = (parsed as { chapters?: unknown }).chapters;
  if (!Array.isArray(chapters)) {
    throw new Error('Stage 3 artifact JSON must have a top-level "chapters" array — see the Generator prompt contract in CLAUDE.md.');
  }
  return { chapters: chapters as ParsedBeatsArtifact["chapters"] };
}

// Writes the approved Stage 3 Beats into the existing Outliner tables —
// manuscript_chapters (creating a stub chapter row if one doesn't exist
// yet for that number, same create-if-missing pattern as
// saveManuscriptScene) and chapter_beats. This is what makes "the chapter
// beats live in the outline panel that exists in the UI" literally true:
// no new UI, no new table the Outliner doesn't already read from.
async function materializeBeats(bookId: string, userId: string, beatsArtifactJson: string): Promise<void> {
  const supabase = getSupabaseClient();
  const { chapters } = parseBeatsArtifact(beatsArtifactJson);

  for (const chapter of chapters) {
    const { data: existing, error: fetchError } = await supabase
      .from("manuscript_chapters")
      .select("id")
      .eq("book_id", bookId)
      .eq("number", chapter.chapterNumber)
      .maybeSingle();
    if (fetchError) throw new Error(`Failed to check chapter ${chapter.chapterNumber}: ${fetchError.message}`);

    let chapterId = existing?.id as string | undefined;
    if (!chapterId) {
      const { data: created, error: insertError } = await supabase
        .from("manuscript_chapters")
        .insert({ user_id: userId, book_id: bookId, number: chapter.chapterNumber, title: chapter.title ?? null, paragraphs: [] })
        .select("id")
        .single();
      if (insertError) throw new Error(`Failed to create chapter ${chapter.chapterNumber}: ${insertError.message}`);
      chapterId = created.id;
    }

    const beatRows = chapter.beats.map((beat, index) => ({
      chapter_id: chapterId,
      order_index: index,
      title: beat.title,
      outline_text: beat.outlineText,
      status: "planned",
    }));
    if (beatRows.length > 0) {
      const { error: beatsError } = await supabase.from("chapter_beats").insert(beatRows);
      if (beatsError) throw new Error(`Failed to create beats for chapter ${chapter.chapterNumber}: ${beatsError.message}`);
    }
  }
}

// Writer approves the artifact at the human review gate. Stage 3 (Beats)
// approval also materializes the beats into the Outliner and kicks off
// entity extraction, instead of finishing outright. Approving the final
// stage marks the run done.
export async function approveStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const next = nextStage(run.current_stage);

  if (run.current_stage === "stage_3_beats") {
    try {
      await materializeBeats(run.book_id, run.user_id, run.stage_artifacts.stage_3_beats ?? "{}");
    } catch (error) {
      return markFailed(runId, error);
    }
    return extractEntities(runId);
  }

  if (!next) {
    return saveRun(runId, { status: "done" });
  }

  return saveRun(runId, {
    current_stage: next,
    status: "generating",
    panel_reviews: null,
    arbitrator_synthesis: null,
    chat_history: [],
  });
}

// Writer rejects the artifact — opens the Arbitrator chat interview.
export async function rejectStage(runId: string): Promise<PlanningRun> {
  return saveRun(runId, { status: "user_chat_active", chat_history: [] });
}

// One turn of the Arbitrator chat interview. Every prior turn is resent —
// the API is stateless per call, same as every LLM API, Hanami included;
// "memory" only ever exists because the caller resends history, exactly
// like the Chat Assistant and scene-draft-sessions already do elsewhere
// in this project.
export async function chatTurn(runId: string, userMessage: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const artifact = run.stage_artifacts[run.current_stage as Exclude<PlanningStage, "all">] ?? "";
    const prompt = await getActivePrompt(run.book_id, "arbitrator_chat", run.current_stage);

    const history: PlanningChatMessage[] = [...run.chat_history, { role: "user", content: userMessage }];

    const anthropic = getAnthropicClient();
    const contextPreamble = interpolateTemplate(prompt.user_prompt_template, {
      CURRENT_ARTIFACT: artifact,
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
    });

    const response = await anthropic.messages.create({
      model: prompt.model,
      max_tokens: 2048,
      system: prompt.system_prompt,
      thinking: { type: "adaptive" },
      output_config: { effort: prompt.effort },
      messages: [
        { role: "user", content: contextPreamble },
        ...history.map((m) => ({ role: m.role, content: m.content })),
      ],
    });

    const reply = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();

    return saveRun(runId, { chat_history: [...history, { role: "assistant", content: reply }] });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Compiles the chat interview into one crisp technical directive, then
// loops back to the Generator for this same stage per the pipeline's own
// diagram (reject -> chat -> directive -> regenerate).
export async function finalizeDirective(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "arbitrator_directive", run.current_stage);
    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      CHAT_HISTORY: JSON.stringify(run.chat_history, null, 2),
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
      CURRENT_ARTIFACT: run.stage_artifacts[run.current_stage as Exclude<PlanningStage, "all">] ?? "",
    });

    const directive = await callAgent({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    return saveRun(runId, { status: "generating", final_delta_directive: directive, chat_history: [] });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// After Stage 3 (Beats) is approved: reads the approved beats artifact and
// proposes Codex/World Category candidates — never written directly, only
// staged here for the writer's batch review (confirmEntities). This is
// the "we won't have to do that by hand" piece, but still keeps "nothing
// writes unsupervised" true — the writer reviews a list, not eyeballing a
// raw model output.
async function extractEntities(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "entity_extractor", "all");
    const bookContext = await buildBookContext(run.book_id);
    const artifact = run.stage_artifacts.stage_3_beats ?? "";

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      BOOK_CONTEXT: bookContext,
      CURRENT_ARTIFACT: artifact,
    });

    const raw = await callAgentForJson({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    const candidates = Array.isArray(raw) ? (raw as ExtractedEntityCandidate[]) : [];

    return saveRun(runId, { status: "awaiting_entity_review", extracted_entities: candidates });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Writer's batch review of extracted entities: writes only the approved
// indexes into the real codex_entries/world_categories tables, via the
// same tables (not a parallel copy) the rest of the product already
// reads and writes. Also inserts the approved Stage 3 beats into
// chapter_beats — the existing Outliner's own table — so the plan shows
// up in the same board/panel already built, with no new UI surface
// needed for beats themselves.
export async function confirmEntities(runId: string, approvedIndexes: number[]): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const supabase = getSupabaseClient();
  const candidates = run.extracted_entities ?? [];

  for (const index of approvedIndexes) {
    const candidate = candidates[index];
    if (!candidate) continue;

    if (candidate.type === "codex_entry") {
      const { error } = await supabase.from("codex_entries").insert({
        user_id: run.user_id,
        book_id: run.book_id,
        name: candidate.name,
        entry_type: candidate.entryType ?? "character",
        description: candidate.description ?? "",
      });
      if (error) throw new Error(`Failed to create Codex entry "${candidate.name}": ${error.message}`);
    } else if (candidate.type === "world_category") {
      const { error } = await supabase.from("world_categories").insert({
        book_id: run.book_id,
        key: candidate.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
        name: candidate.name,
        description: candidate.description ?? null,
      });
      if (error && error.code !== "23505") throw new Error(`Failed to create world category "${candidate.name}": ${error.message}`);
    }
  }

  return saveRun(runId, { status: "done", extracted_entities: null });
}
