import { getAnthropicClient } from "../lib/anthropicClient.js";
import { getSupabaseClient } from "../lib/supabaseClient.js";
import { getActivePrompt, interpolateTemplate } from "./agentPrompts.js";
import { getBookFacts, formatBookFactsSection } from "./bookFacts.js";
import { listCodexEntries } from "./bookContextTools.js";
import { getPlatformCraftNotes } from "./platformCraftNotes.js";
import { ACTS_PER_BOOK, CRITIC_ROLES, PARTS_PER_ACT } from "../types/domain.js";
import type Anthropic from "@anthropic-ai/sdk";
import type {
  AgentRole,
  ContinuityLedgerEntry,
  EffortLevel,
  ExtractedEntityCandidate,
  PartChapterRange,
  PipelineType,
  PlanningChatMessage,
  PlanningRun,
  RealPlanningStage,
} from "../types/domain.js";

// The Webnovel Planning Engine: Stage 1 Core Summary, then a strict,
// incremental Act -> Part -> Beats hierarchy — 3 fixed Acts, each with 3
// fixed Parts, each Part planned as an outline pass then a beats pass —
// every unit generated by Claude ("Generator" here means planning text —
// summaries/outlines/beats, NEVER manuscript prose, which stays
// exclusively Hanami's job via the existing /generate-prose and MCP
// tools), critiqued by a 3-critic panel, synthesized by an Arbitrator,
// and gated on human approval before advancing. Every agent's behavior is
// entirely prompt-driven — every system_prompt/user_prompt_template is
// authored by the writer via the Prompt Editor (src/services/agentPrompts.ts)
// and stored in agent_prompts; this file only supplies the mechanics that
// make those prompts actually run reliably (the loop, the interpolation,
// structured JSON verification with a retry, and where each artifact/
// context slot comes from) — it contains no prompt content of its own.
//
// Replaced a flat 3-stage model (Summary -> whole-book Acts -> whole-book
// Beats) after confirming live that a single call planning an entire
// book's act structure at once produces real internal contradictions — a
// heist book's own stated numbers (bearer-core weights, manifest
// tolerances) disagreeing with each other by the time the model reached
// arc 4-5, caught by the Continuity Critic on its very first real test.
// Nothing here plans further ahead than the writer has actually approved,
// and every unit gets three layers of context: the book-wide vision
// (Stage 1's summary, permanent at every depth — never diluted by only
// passing through one hop at a time), the immediate parent unit it's
// expanding, and a continuity ledger of hard facts, reconciled against
// the real manuscript wherever chapters have actually been drafted.

// Chapters worth of beats generated per part_beats call — a Part can span
// far more chapters than one call should try to hold coherently (the same
// reasoning that ended whole-book Acts generation applies one level down).
// Not exposed via the API yet; a plain constant to tune here as real usage
// accumulates, the same as this project's other not-yet-calibrated
// constants (Layer 3's match threshold, the context token ceiling).
const PART_BEATS_CHAPTER_WINDOW = 15;

interface UnitPosition {
  // Which track this position belongs to — see PipelineType. Only matters
  // at the one fork point (what comes right after stage_1_summary) and at
  // the "promoted run skips Part 1" special case in nextPosition below;
  // everywhere else the stage alone already disambiguates (codex_
  // documentation/hook_chapters_outline only ever exist in "contract").
  pipelineType: PipelineType;
  stage: RealPlanningStage;
  act: number | null;
  part: number | null;
  beatChunk: number | null;
}

function partRangeKey(act: number, part: number): string {
  return `${act}-${part}`;
}

function chunksNeededForRange(range: PartChapterRange): number {
  const totalChapters = range.endChapter - range.startChapter + 1;
  return Math.max(1, Math.ceil(totalChapters / PART_BEATS_CHAPTER_WINDOW));
}

function chunkChapterRange(range: PartChapterRange, chunkIndex: number): PartChapterRange {
  const start = range.startChapter + (chunkIndex - 1) * PART_BEATS_CHAPTER_WINDOW;
  const end = Math.min(range.startChapter + chunkIndex * PART_BEATS_CHAPTER_WINDOW - 1, range.endChapter);
  return { startChapter: start, endChapter: end };
}

function unitKey(pos: UnitPosition): string {
  switch (pos.stage) {
    case "stage_1_summary":
      return "stage_1_summary";
    case "codex_documentation":
      return "codex_documentation";
    case "hook_chapters_outline":
      return "hook_chapters_outline";
    case "act_summary":
      return `act_${pos.act}_summary`;
    case "part_outline":
      return `act_${pos.act}_part_${pos.part}_outline`;
    case "part_beats":
      return `act_${pos.act}_part_${pos.part}_beats_chunk_${pos.beatChunk}`;
  }
}

function currentPosition(run: PlanningRun): UnitPosition {
  return {
    pipelineType: run.pipeline_type,
    stage: run.current_stage as RealPlanningStage,
    act: run.current_act,
    part: run.current_part,
    beatChunk: run.current_beat_chunk,
  };
}

function currentUnitKey(run: PlanningRun): string {
  return unitKey(currentPosition(run));
}

// What comes after `pos`, given the run's part_chapter_ranges (needed to
// know how many beat-generation chunks a Part needs). Null once all 3
// Acts' all 9 Parts are fully planned — the whole book.
function nextPosition(pos: UnitPosition, partChapterRanges: Record<string, PartChapterRange>): UnitPosition | null {
  if (pos.stage === "stage_1_summary") {
    if (pos.pipelineType === "contract") {
      return { ...pos, stage: "codex_documentation", act: null, part: null, beatChunk: null };
    }
    return { ...pos, stage: "act_summary", act: 1, part: null, beatChunk: null };
  }
  if (pos.stage === "codex_documentation") {
    return { ...pos, stage: "hook_chapters_outline", act: null, part: null, beatChunk: null };
  }
  if (pos.stage === "hook_chapters_outline") {
    // The Contract Pipeline is exactly these three units — done once this
    // is approved. See promoteContractRunToFull for how an approved run
    // continues into the main hierarchy, as a brand new "full" run.
    return null;
  }
  if (pos.stage === "act_summary") {
    // A run created by promoteContractRunToFull already has Part 1
    // (chapters 1-5) materialized before Act 1's summary is even
    // generated — its chapter range was pre-seeded. Skip straight to
    // Part 2 rather than re-planning a Part that's already written and
    // approved via the Contract Pipeline.
    if (pos.act === 1 && partChapterRanges[partRangeKey(1, 1)]) {
      return { ...pos, stage: "part_outline", part: 2, beatChunk: null };
    }
    return { ...pos, stage: "part_outline", part: 1, beatChunk: null };
  }
  if (pos.stage === "part_outline") {
    return { ...pos, stage: "part_beats", beatChunk: 1 };
  }
  // part_beats
  const range = partChapterRanges[partRangeKey(pos.act as number, pos.part as number)];
  const totalChunks = range ? chunksNeededForRange(range) : 1;
  if ((pos.beatChunk ?? 1) < totalChunks) {
    return { ...pos, beatChunk: (pos.beatChunk ?? 1) + 1 };
  }
  if ((pos.part as number) < PARTS_PER_ACT) {
    return { ...pos, stage: "part_outline", part: (pos.part as number) + 1, beatChunk: null };
  }
  if ((pos.act as number) < ACTS_PER_BOOK) {
    return { ...pos, stage: "act_summary", act: (pos.act as number) + 1, part: null, beatChunk: null };
  }
  return null;
}

// Mirror of nextPosition — the unit BEFORE `pos`, used by
// unapproveStage/discardStage. Null if `pos` is the very first unit.
// Note: deliberately does NOT mirror nextPosition's "skip Part 1" special
// case for a promoted run — stepping back from Act 1 Part 2's outline
// before anything else has been generated would fall through to Part 1's
// beats position, which (for a promoted run) was never generated through
// this run's own cycle and has no real critique history to restore. A
// rare, low-stakes edge case (unapprove/discard immediately after the
// very first generation of a promoted run) rather than something worth
// the extra branching to special-case here too.
function previousPosition(pos: UnitPosition, partChapterRanges: Record<string, PartChapterRange>): UnitPosition | null {
  if (pos.stage === "stage_1_summary") return null;
  if (pos.stage === "codex_documentation") {
    return { ...pos, stage: "stage_1_summary", act: null, part: null, beatChunk: null };
  }
  if (pos.stage === "hook_chapters_outline") {
    return { ...pos, stage: "codex_documentation", act: null, part: null, beatChunk: null };
  }
  if (pos.stage === "act_summary") {
    if ((pos.act as number) === 1) return { ...pos, stage: "stage_1_summary", act: null, part: null, beatChunk: null };
    const prevAct = (pos.act as number) - 1;
    const range = partChapterRanges[partRangeKey(prevAct, PARTS_PER_ACT)];
    const lastChunk = range ? chunksNeededForRange(range) : 1;
    return { ...pos, stage: "part_beats", act: prevAct, part: PARTS_PER_ACT, beatChunk: lastChunk };
  }
  if (pos.stage === "part_outline") {
    if ((pos.part as number) === 1) return { ...pos, stage: "act_summary", part: null, beatChunk: null };
    const prevPart = (pos.part as number) - 1;
    const range = partChapterRanges[partRangeKey(pos.act as number, prevPart)];
    const lastChunk = range ? chunksNeededForRange(range) : 1;
    return { ...pos, stage: "part_beats", part: prevPart, beatChunk: lastChunk };
  }
  // part_beats
  if ((pos.beatChunk ?? 1) > 1) {
    return { ...pos, beatChunk: (pos.beatChunk ?? 1) - 1 };
  }
  return { ...pos, stage: "part_outline", beatChunk: null };
}

// The immediate parent unit's approved content — what this unit is a
// detailed expansion of. Distinct from BOOK_VISION (always Stage 1,
// regardless of depth) and from CONTINUITY_LEDGER (hard facts, not prose).
function parentArtifactFor(run: PlanningRun): string {
  const pos = currentPosition(run);
  if (pos.stage === "stage_1_summary") return "";
  if (pos.stage === "codex_documentation") return run.stage_artifacts["stage_1_summary"] ?? "";
  if (pos.stage === "hook_chapters_outline") return run.stage_artifacts["codex_documentation"] ?? "";
  if (pos.stage === "act_summary") return run.stage_artifacts["stage_1_summary"] ?? "";
  if (pos.stage === "part_outline") return run.stage_artifacts[`act_${pos.act}_summary`] ?? "";
  return run.stage_artifacts[`act_${pos.act}_part_${pos.part}_outline`] ?? "";
}

function formatLedger(ledger: ContinuityLedgerEntry[]): string {
  if (ledger.length === 0) return "";
  return ledger.map((e) => `- [${e.sourcedFrom}] ${e.fact} (from ${e.unit})`).join("\n");
}

async function loadRun(runId: string): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from("planning_runs").select("*").eq("id", runId).maybeSingle();
  if (error) throw new Error(`Failed to load planning run: ${error.message}`);
  if (!data) throw new Error(`No planning run found with id ${runId}.`);
  return data as PlanningRun;
}

async function saveRun(runId: string, patch: Record<string, unknown>): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .update({ ...patch, updated_at: new Date().toISOString() })
    .eq("id", runId)
    .select("*")
    .single();
  if (error) throw new Error(`Failed to update planning run: ${error.message}`);
  return data as PlanningRun;
}

// Marks the run failed with a clear message rather than leaving it stuck
// in an intermediate status with no explanation — the one thing worse
// than a failed pipeline step is a silent one. Only for failures in the
// MAIN pipeline flow (generate/critique/arbitrate/approve) — a side
// action like extractEntities must NOT call this, since it would
// incorrectly flip the whole run's displayed status to 'failed' over a
// side action's error while the real pipeline position is perfectly fine.
async function markFailed(runId: string, error: unknown): Promise<never> {
  const message = error instanceof Error ? error.message : String(error);
  await saveRun(runId, { status: "failed", last_error: message });
  throw error instanceof Error ? error : new Error(message);
}

// 8000 was too low, confirmed live: a Generator call at effort "high" with
// a full-book BOOK_CONTEXT (hundreds of chapters' worth of Codex) can spend
// its entire token budget on adaptive thinking before emitting any visible
// text, returning an empty string with no error — a real result observed
// in production, not a hypothetical. 16000 matches this project's own
// established default for non-streaming Claude calls; still comfortably
// under the SDK's request timeout even on a call that runs a couple of
// minutes, which these can.
const DEFAULT_MAX_TOKENS = 16000;

async function callAgent(params: { systemPrompt: string; userMessage: string; model: string; effort: EffortLevel; maxTokens?: number }): Promise<string> {
  const anthropic = getAnthropicClient();
  const response = await anthropic.messages.create({
    model: params.model,
    max_tokens: params.maxTokens ?? DEFAULT_MAX_TOKENS,
    system: params.systemPrompt,
    thinking: { type: "adaptive" },
    output_config: { effort: params.effort },
    messages: [{ role: "user", content: params.userMessage }],
  });

  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n")
    .trim();

  // Verify, don't just trust — an empty result with stop_reason
  // "max_tokens" (thinking consumed the whole budget) previously saved
  // silently and let the run advance as if it had succeeded. Fail loudly
  // instead, with enough detail to actually diagnose it.
  if (!text) {
    throw new Error(
      `Agent returned no text output (stop_reason: ${response.stop_reason}). This usually means max_tokens was exhausted by thinking before any visible output — try raising max_tokens or lowering effort for this prompt.`
    );
  }

  return text;
}

function tryParseJson(text: string): unknown | undefined {
  const stripped = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "")
    .trim();
  try {
    return JSON.parse(stripped);
  } catch {
    const match = stripped.match(/[[{][\s\S]*[\]}]/);
    if (!match) return undefined;
    try {
      return JSON.parse(match[0]);
    } catch {
      return undefined;
    }
  }
}

// Verify, don't just trust the instruction — same principle Ghost Editor
// already established for banned terms in this project. A critic/
// arbitrator prompt asks for JSON; this checks the response actually is
// valid JSON and gives the model exactly one corrective retry before
// surfacing a real failure, rather than silently storing garbage or
// silently accepting prose instead of the requested structure.
async function callAgentForJson(params: { systemPrompt: string; userMessage: string; model: string; effort: EffortLevel }): Promise<unknown> {
  const first = await callAgent(params);
  const parsedFirst = tryParseJson(first);
  if (parsedFirst !== undefined) return parsedFirst;

  const retryMessage = `${params.userMessage}\n\nYour previous response was not valid JSON. Return ONLY a single valid JSON object or array — no surrounding prose, no markdown code fences.`;
  const second = await callAgent({ ...params, userMessage: retryMessage });
  const parsedSecond = tryParseJson(second);
  if (parsedSecond !== undefined) return parsedSecond;

  throw new Error("Agent did not return valid JSON after one corrective retry.");
}

async function buildBookContext(bookId: string): Promise<string> {
  const [facts, codexEntries] = await Promise.all([getBookFacts(bookId), listCodexEntries(bookId)]);
  return [formatBookFactsSection(facts), "", "## Codex Entries", "", JSON.stringify(codexEntries, null, 2)].join("\n");
}

// New runs start in the intake conversation, not mid-generation — there's
// nothing for the Generator to work from until the writer has actually
// described what this book is, via intakeChatTurn/finalizeIntake below.
// pipelineType defaults to "full"; pass "contract" to start the shorter
// hook-chapters track instead (see PipelineType). Both share the exact
// same intake flow and Stage 1 Summary — they only diverge afterward, in
// nextPosition.
export async function createPlanningRun(params: {
  bookId: string;
  userId: string;
  pipelineType?: PipelineType;
}): Promise<PlanningRun> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .insert({
      book_id: params.bookId,
      user_id: params.userId,
      pipeline_type: params.pipelineType ?? "full",
      status: "intake_active",
    })
    .select("*")
    .single();
  if (error) throw new Error(`Failed to create planning run: ${error.message}`);
  return data as PlanningRun;
}

// Starts a new run reusing another run's ALREADY-APPROVED Stage 1 Summary
// rather than regenerating one fresh via intake — for testing a different
// pipeline against a book whose Core Summary is already settled (e.g.
// trying the Contract Pipeline against the real book's existing full-
// pipeline summary, without re-running intake or paying for a duplicate
// Stage 1 generation). The source run just needs to have gotten PAST
// stage_1_summary at some point — stage_artifacts accumulates and is
// never cleared for already-approved units, so this works whether the
// source run is still in progress or fully done. Skips straight past
// Stage 1 to whatever unit comes right after it for the requested track
// (codex_documentation for "contract", Act 1 Summary for "full") via the
// same nextPosition every other transition in this file uses.
export async function createPlanningRunFromExistingSummary(params: {
  sourceRunId: string;
  userId: string;
  pipelineType: PipelineType;
}): Promise<PlanningRun> {
  const sourceRun = await loadRun(params.sourceRunId);
  const summary = sourceRun.stage_artifacts["stage_1_summary"];
  if (!summary) {
    throw new Error("The source run has no approved Stage 1 Summary yet to reuse.");
  }

  const startPos = nextPosition(
    { pipelineType: params.pipelineType, stage: "stage_1_summary", act: null, part: null, beatChunk: null },
    {}
  );
  if (!startPos) {
    throw new Error(`No unit follows stage_1_summary for pipeline type "${params.pipelineType}".`);
  }

  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .insert({
      book_id: sourceRun.book_id,
      user_id: params.userId,
      pipeline_type: params.pipelineType,
      status: "generating",
      current_stage: startPos.stage,
      current_act: startPos.act,
      current_part: startPos.part,
      current_beat_chunk: startPos.beatChunk,
      stage_artifacts: { stage_1_summary: summary },
    })
    .select("*")
    .single();
  if (error) throw new Error(`Failed to create planning run from existing summary: ${error.message}`);
  return data as PlanningRun;
}

// A completed ("done") Contract Pipeline run hands off into the main
// hierarchy as a brand new "full" run for the SAME book, seeded rather
// than starting cold: Stage 1 reuses the already-approved summary (no
// regeneration), Part 1 of Act 1 (chapters 1-5) is pre-recorded as already
// materialized — real chapter/beat rows already exist in the Outliner
// from the Contract Pipeline's own hook_chapters_outline approval — and
// the continuity ledger carries over whatever facts were already
// extracted from those chapters. The new run starts at Act 1's summary
// (still genuinely generated fresh, informed by what was actually
// written) and nextPosition's "skip Part 1" special case takes it
// straight to Part 2's outline once that's approved. The original
// contract run is left untouched — a new row, not a mutation — so it
// stays as an intact historical record of what actually got the contract.
export async function promoteContractRunToFull(contractRunId: string): Promise<PlanningRun> {
  const seedRun = await loadRun(contractRunId);
  if (seedRun.pipeline_type !== "contract") {
    throw new Error("Only a Contract Pipeline run can be promoted to the full pipeline.");
  }
  if (seedRun.status !== "done") {
    throw new Error(
      "This Contract Pipeline run must be fully approved (status: done) before promoting it — the Codex documentation and the five hook chapters need to be locked in first."
    );
  }

  const supabase = getSupabaseClient();
  const summary = seedRun.stage_artifacts["stage_1_summary"] ?? "";
  const hookBeats = seedRun.stage_artifacts["hook_chapters_outline"] ?? "{}";
  const part1OutlineKey = unitKey({ pipelineType: "full", stage: "part_outline", act: 1, part: 1, beatChunk: null });
  const part1BeatsKey = unitKey({ pipelineType: "full", stage: "part_beats", act: 1, part: 1, beatChunk: 1 });

  const { data, error } = await supabase
    .from("planning_runs")
    .insert({
      book_id: seedRun.book_id,
      user_id: seedRun.user_id,
      pipeline_type: "full",
      status: "generating",
      current_stage: "act_summary",
      current_act: 1,
      current_part: null,
      current_beat_chunk: null,
      part_chapter_ranges: { [partRangeKey(1, 1)]: { startChapter: 1, endChapter: 5 } },
      continuity_ledger: seedRun.continuity_ledger,
      stage_artifacts: {
        stage_1_summary: summary,
        // Display-only placeholder — Part 1 never goes through its own
        // outline review gate on this run (it was already reviewed as the
        // Contract Pipeline's hook_chapters_outline unit); this just keeps
        // the Pipeline Map from showing an unexplained gap for it.
        [part1OutlineKey]:
          "Chapters 1-5 were already planned and approved via the Contract Pipeline — see the Codex and this Part's Beats for full detail.",
        [part1BeatsKey]: hookBeats,
      },
    })
    .select("*")
    .single();
  if (error) throw new Error(`Failed to promote Contract Pipeline run to the full pipeline: ${error.message}`);
  return data as PlanningRun;
}

export async function getPlanningRun(runId: string): Promise<PlanningRun> {
  return loadRun(runId);
}

// Every run's state lives entirely server-side — a step endpoint writes
// its result to planning_runs immediately, nothing is held in frontend
// memory. But until now the only way to find a specific run was to
// already have its id, normally carried in the frontend's URL — lose
// that (closed tab, browser history cleared, opening the book on a
// different device) and a fully intact, in-progress run became
// unreachable even though nothing was actually lost. This is what lets
// the frontend resolve "what's this book's current planning run" on its
// own instead of depending on a URL surviving.
export async function listPlanningRuns(bookId: string): Promise<PlanningRun[]> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("planning_runs")
    .select("*")
    .eq("book_id", bookId)
    .order("updated_at", { ascending: false });
  if (error) throw new Error(`Failed to list planning runs: ${error.message}`);
  return (data ?? []) as PlanningRun[];
}

// Abandons a run outright — for a diagnostic/test run, or one the writer
// just wants to discard. No confirm-gate needed here the way entity
// writes have one: this only ever removes the run's own bookkeeping row,
// never anything it may have already materialized into chapter_beats or
// codex_entries (those are separate, real content and are cleaned up, if
// at all, through their own normal delete endpoints).
export async function deletePlanningRun(runId: string): Promise<void> {
  const supabase = getSupabaseClient();
  const { error, count } = await supabase.from("planning_runs").delete({ count: "exact" }).eq("id", runId);
  if (error) throw new Error(`Failed to delete planning run: ${error.message}`);
  if (!count) throw new Error(`No planning run found with id ${runId}.`);
}

// Runs the Generator for the run's current unit. Every call gets three
// layers of context: BOOK_VISION (Stage 1's summary — permanent at every
// depth, never diluted by only cascading one hop at a time),
// PARENT_ARTIFACT (the immediate parent unit this one is expanding), and
// CONTINUITY_LEDGER (hard facts from everything approved so far,
// reconciled against the real manuscript wherever it's been drafted —
// see appendLedgerFacts). Plus BOOK_CONTEXT (existing Codex/facts, for
// continuing an already-written book) and, on a revision, PREVIOUS_ARTIFACT
// (this exact unit's own last draft) and FINAL_DELTA_DIRECTIVE.
export async function generateStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const unit = currentUnitKey(run);
    const prompt = await getActivePrompt(run.book_id, "generator", run.current_stage);
    const bookContext = await buildBookContext(run.book_id);
    const bookVision = run.stage_artifacts["stage_1_summary"] ?? "";
    const parentArtifact = parentArtifactFor(run);
    const ledgerText = formatLedger(run.continuity_ledger);
    // This exact unit's own last draft — empty on a first generation,
    // populated on a revision. Read before this call overwrites it below.
    const previousArtifact = run.stage_artifacts[unit] ?? "";

    let chapterRangeText = "";
    if (run.current_stage === "part_beats") {
      const range = run.part_chapter_ranges[partRangeKey(run.current_act as number, run.current_part as number)];
      if (!range) {
        throw new Error(
          `No chapter range recorded for Act ${run.current_act} Part ${run.current_part} — its outline must be approved with a valid startChapter/endChapter before beats can be generated.`
        );
      }
      const chunk = chunkChapterRange(range, run.current_beat_chunk ?? 1);
      chapterRangeText = `Chapters ${chunk.startChapter}-${chunk.endChapter} (this Part's full range is ${range.startChapter}-${range.endChapter}).`;
    } else if (run.current_stage === "hook_chapters_outline") {
      // Fixed, not model-decided — same "AI can never go against it"
      // principle as ACTS_PER_BOOK/PARTS_PER_ACT. The Contract Pipeline
      // always covers exactly chapters 1-5.
      chapterRangeText = "Chapters 1-5 (fixed — the Contract Pipeline always covers exactly the first five chapters).";
    }

    // Only relevant to the Contract Pipeline's hook-focused units — see
    // platformCraftNotes.ts. Harmless to fetch/pass unconditionally for
    // "contract" runs even on stage_1_summary/codex_documentation, since
    // interpolateTemplate silently ignores a value no placeholder in the
    // template actually references.
    const platformTrends =
      run.pipeline_type === "contract" ? ((await getPlatformCraftNotes(run.book_id))?.content ?? "") : "";

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      BOOK_CONTEXT: bookContext,
      BOOK_VISION: bookVision,
      PARENT_ARTIFACT: parentArtifact,
      CONTINUITY_LEDGER: ledgerText,
      PREVIOUS_ARTIFACT: previousArtifact,
      FINAL_DELTA_DIRECTIVE: run.final_delta_directive ?? "",
      CHAPTER_RANGE: chapterRangeText,
      PLATFORM_TRENDS: platformTrends,
    });

    // part_outline, part_beats, codex_documentation, and hook_chapters_
    // outline all come back as structured JSON — part_outline commits to
    // a real chapter range (parsed by approveStage to record part_chapter_
    // ranges), part_beats and hook_chapters_outline get parsed straight
    // into chapter_beats rows on approval (materializeBeats — the same
    // JSON contract for both), codex_documentation gets parsed straight
    // into codex_entries rows on approval (materializeCodexDocumentation).
    // act_summary and stage_1_summary stay plain text — they're meant to
    // be read, not parsed.
    const isJsonUnit =
      run.current_stage === "part_outline" ||
      run.current_stage === "part_beats" ||
      run.current_stage === "codex_documentation" ||
      run.current_stage === "hook_chapters_outline";
    const artifact = isJsonUnit
      ? JSON.stringify(
          await callAgentForJson({ systemPrompt: prompt.system_prompt, userMessage, model: prompt.model, effort: prompt.effort })
        )
      : await callAgent({ systemPrompt: prompt.system_prompt, userMessage, model: prompt.model, effort: prompt.effort });

    return saveRun(runId, {
      status: "critiquing",
      stage_artifacts: { ...run.stage_artifacts, [unit]: artifact },
      final_delta_directive: null,
    });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Fires every critic in CRITIC_ROLES in parallel — one bounded request per
// critic, not a chain — against the unit that was just generated. Each
// critic gets BOOK_VISION and CONTINUITY_LEDGER too (not just the
// Generator) — the Continuity Critic specifically needs the ledger to
// actually check for contradictions, not just the current artifact in
// isolation. Each critic also gets its OWN previous review of this same
// unit (if one exists) via {{PREVIOUS_CRITIQUE}} — read from
// run.panel_reviews before this call's new reviews overwrite it, the same
// "read the value right before it's replaced" trick generateStage already
// uses for {{PREVIOUS_ARTIFACT}}. Deliberately not a persisted chat
// session (see CLAUDE.md's note on why that was rejected): each call
// stays a single bounded review, so cost never grows across revisions.
export async function runCritique(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const unit = currentUnitKey(run);
    const artifact = run.stage_artifacts[unit] ?? "";
    const bookContext = await buildBookContext(run.book_id);
    const bookVision = run.stage_artifacts["stage_1_summary"] ?? "";
    const ledgerText = formatLedger(run.continuity_ledger);
    const previousPanelReviews = run.panel_reviews ?? {};
    const platformTrends =
      run.pipeline_type === "contract" ? ((await getPlatformCraftNotes(run.book_id))?.content ?? "") : "";

    const prompts = await Promise.all(CRITIC_ROLES.map((role) => getActivePrompt(run.book_id, role, run.current_stage)));

    const reviews = await Promise.all(
      prompts.map((prompt, i) => {
        const role = CRITIC_ROLES[i] as AgentRole;
        const previousCritique = previousPanelReviews[role];
        return callAgentForJson({
          systemPrompt: prompt.system_prompt,
          userMessage: interpolateTemplate(prompt.user_prompt_template, {
            BOOK_CONTEXT: bookContext,
            BOOK_VISION: bookVision,
            CONTINUITY_LEDGER: ledgerText,
            CURRENT_ARTIFACT: artifact,
            PREVIOUS_CRITIQUE: previousCritique !== undefined ? JSON.stringify(previousCritique, null, 2) : "",
            PLATFORM_TRENDS: platformTrends,
          }),
          model: prompt.model,
          effort: prompt.effort,
        });
      })
    );

    const panelReviews: Partial<Record<AgentRole, unknown>> = {};
    CRITIC_ROLES.forEach((role, i) => {
      panelReviews[role] = reviews[i];
    });

    return saveRun(runId, { status: "awaiting_arbitration", panel_reviews: panelReviews });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Arbitrator's panel-synthesis pass: compiles all three critiques into
// whatever form the writer's own prompt asks for, then opens the human
// review gate.
export async function runArbitration(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const unit = currentUnitKey(run);
    const artifact = run.stage_artifacts[unit] ?? "";
    const prompt = await getActivePrompt(run.book_id, "arbitrator_panel", run.current_stage);
    const bookVision = run.stage_artifacts["stage_1_summary"] ?? "";
    // Read before this call's new synthesis overwrites it — same
    // previous-verdict trick runCritique uses for {{PREVIOUS_CRITIQUE}}.
    const previousSynthesis = run.arbitrator_synthesis;
    const platformTrends =
      run.pipeline_type === "contract" ? ((await getPlatformCraftNotes(run.book_id))?.content ?? "") : "";

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      BOOK_VISION: bookVision,
      CURRENT_ARTIFACT: artifact,
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
      PREVIOUS_SYNTHESIS: previousSynthesis != null ? JSON.stringify(previousSynthesis, null, 2) : "",
      PLATFORM_TRENDS: platformTrends,
    });

    const synthesis = await callAgentForJson({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    return saveRun(runId, { status: "awaiting_user_review", arbitrator_synthesis: synthesis });
  } catch (error) {
    return markFailed(runId, error);
  }
}

interface ParsedBeatsArtifact {
  chapters: { chapterNumber: number; title?: string; beats: { title: string; outlineText: string }[] }[];
}

function parseBeatsArtifact(raw: string): ParsedBeatsArtifact {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Beats artifact is not valid JSON — cannot materialize beats into the Outliner.");
  }
  const chapters = (parsed as { chapters?: unknown }).chapters;
  if (!Array.isArray(chapters)) {
    throw new Error('Beats artifact JSON must have a top-level "chapters" array — see the part_beats Generator prompt contract in CLAUDE.md.');
  }
  return { chapters: chapters as ParsedBeatsArtifact["chapters"] };
}

interface ParsedPartOutline {
  startChapter: number;
  endChapter: number;
}

// part_outline's JSON must commit to a real chapter range — the first
// point in the hierarchy concrete enough to do so — so part_beats knows
// how many beat-generation chunks this Part needs and materializeBeats
// knows where to place its chapters.
function parsePartOutlineArtifact(raw: string): ParsedPartOutline {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Part outline artifact is not valid JSON — cannot record its chapter range.");
  }
  const obj = parsed as { startChapter?: unknown; endChapter?: unknown };
  if (typeof obj.startChapter !== "number" || typeof obj.endChapter !== "number") {
    throw new Error(
      'Part outline JSON must include numeric "startChapter" and "endChapter" — see the part_outline Generator prompt contract in CLAUDE.md.'
    );
  }
  if (obj.endChapter < obj.startChapter) {
    throw new Error(`Part outline's endChapter (${obj.endChapter}) is before its startChapter (${obj.startChapter}).`);
  }
  return { startChapter: obj.startChapter, endChapter: obj.endChapter };
}

// Writes an approved part_beats chunk into the existing Outliner tables —
// manuscript_chapters (creating a stub chapter row if one doesn't exist
// yet for that number, same create-if-missing pattern as
// saveManuscriptScene) and chapter_beats. Runs per CHUNK now, not once for
// the whole book — beats show up in the Outliner as soon as each chunk is
// approved, not after the entire 9-Part book is done.
async function materializeBeats(bookId: string, userId: string, beatsArtifactJson: string): Promise<void> {
  const supabase = getSupabaseClient();
  const { chapters } = parseBeatsArtifact(beatsArtifactJson);

  for (const chapter of chapters) {
    const { data: existing, error: fetchError } = await supabase
      .from("manuscript_chapters")
      .select("id")
      .eq("book_id", bookId)
      .eq("number", chapter.chapterNumber)
      .maybeSingle();
    if (fetchError) throw new Error(`Failed to check chapter ${chapter.chapterNumber}: ${fetchError.message}`);

    let chapterId = existing?.id as string | undefined;
    if (!chapterId) {
      const { data: created, error: insertError } = await supabase
        .from("manuscript_chapters")
        .insert({ user_id: userId, book_id: bookId, number: chapter.chapterNumber, title: chapter.title ?? null, paragraphs: [] })
        .select("id")
        .single();
      if (insertError) throw new Error(`Failed to create chapter ${chapter.chapterNumber}: ${insertError.message}`);
      chapterId = created.id;
    }

    const beatRows = chapter.beats.map((beat, index) => ({
      chapter_id: chapterId,
      order_index: index,
      title: beat.title,
      outline_text: beat.outlineText,
      status: "planned",
    }));
    if (beatRows.length > 0) {
      // Idempotency guard against a retried approve after a failure later in
      // this same call (e.g. appendLedgerFacts erroring out post-materialize,
      // such as an LLM-billing failure) — markFailed leaves current_stage
      // parked on this exact unit, so a retry re-runs this whole function.
      // Skip any row whose (title, outlineText) already exists for this
      // chapter rather than blind-delete-then-insert, since a chapter can
      // also hold real writer-authored beats from the Outliner's own CRUD
      // surface that must never be discarded as a side effect of this retry.
      const { data: existingBeats, error: existingError } = await supabase
        .from("chapter_beats")
        .select("title, outline_text")
        .eq("chapter_id", chapterId);
      if (existingError) throw new Error(`Failed to check existing beats for chapter ${chapter.chapterNumber}: ${existingError.message}`);
      const existingKeys = new Set((existingBeats ?? []).map((b) => `${b.title} ${b.outline_text}`));
      const newRows = beatRows.filter((r) => !existingKeys.has(`${r.title} ${r.outline_text}`));
      if (newRows.length > 0) {
        const { error: beatsError } = await supabase.from("chapter_beats").insert(newRows);
        if (beatsError) throw new Error(`Failed to create beats for chapter ${chapter.chapterNumber}: ${beatsError.message}`);
      }
    }
  }
}

// After a part_beats chunk is approved: reconciles that chunk's chapter
// range against the REAL manuscript — chapters actually drafted and
// accepted, read from manuscript_chapters.paragraphs (the editor's actual
// content), not manuscript_chunks (the separate, opt-in RAG index a
// chapter might not be synced to yet even once written) — and extracts a
// short list of hard facts worth remembering for the rest of the book.
// Where a chapter hasn't been drafted, falls back to what this chunk's own
// beats claimed. Auto-appends to continuity_ledger with no separate review
// gate — unlike Codex/World Category entries, the ledger isn't new
// writer-facing canon, it's a compressed memory of content that already
// went through its own human review gate (the beats chunk itself).
async function appendLedgerFacts(run: PlanningRun, unit: string, beatsArtifactJson: string): Promise<ContinuityLedgerEntry[]> {
  const { chapters } = parseBeatsArtifact(beatsArtifactJson);
  if (chapters.length === 0) return run.continuity_ledger;

  const supabase = getSupabaseClient();
  const chapterNumbers = chapters.map((c) => c.chapterNumber);
  const { data: manuscriptRows, error } = await supabase
    .from("manuscript_chapters")
    .select("number, paragraphs")
    .eq("book_id", run.book_id)
    .in("number", chapterNumbers);
  if (error) throw new Error(`Failed to check manuscript for ledger reconciliation: ${error.message}`);

  const draftedByNumber = new Map<number, string>();
  for (const row of manuscriptRows ?? []) {
    const paragraphs = row.paragraphs as { text?: string }[] | null;
    if (Array.isArray(paragraphs) && paragraphs.length > 0) {
      draftedByNumber.set(row.number as number, paragraphs.map((p) => p.text ?? "").join("\n\n"));
    }
  }

  const sourcedFrom: "plan" | "manuscript" = draftedByNumber.size > 0 ? "manuscript" : "plan";
  const contentBlocks = chapters.map((chapter) => {
    const drafted = draftedByNumber.get(chapter.chapterNumber);
    if (drafted) return `Chapter ${chapter.chapterNumber} (actually drafted):\n${drafted}`;
    const planText = chapter.beats.map((b) => `- ${b.title}: ${b.outlineText}`).join("\n");
    return `Chapter ${chapter.chapterNumber} (planned only, not drafted yet):\n${planText}`;
  });

  const prompt = await getActivePrompt(run.book_id, "ledger_extractor", "all");
  const userMessage = interpolateTemplate(prompt.user_prompt_template, {
    CONTENT: contentBlocks.join("\n\n"),
    EXISTING_LEDGER: formatLedger(run.continuity_ledger),
  });

  const raw = await callAgentForJson({ systemPrompt: prompt.system_prompt, userMessage, model: prompt.model, effort: prompt.effort });
  const facts = Array.isArray(raw) ? raw.filter((f): f is string => typeof f === "string" && f.trim() !== "") : [];

  const newEntries: ContinuityLedgerEntry[] = facts.map((fact) => ({ fact, sourcedFrom, unit }));
  // Same retry scenario as materializeBeats's idempotency guard above: a
  // unit's ledger contribution is only ever meant to land once. Strip any
  // entries already tagged with this unit before appending the fresh set —
  // the only way they could already be there is a prior failed attempt for
  // this exact still-current unit, never a second legitimate contribution.
  const withoutPriorAttempt = run.continuity_ledger.filter((e) => e.unit !== unit);
  return [...withoutPriorAttempt, ...newEntries];
}

interface ParsedCodexDocumentationArtifact {
  entries: {
    name: string;
    entryType: string;
    description: string;
    aliases?: string[];
    tier?: string;
    personalityTraits?: string[];
    motivations?: string[];
  }[];
}

function parseCodexDocumentationArtifact(raw: string): ParsedCodexDocumentationArtifact {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Codex documentation artifact is not valid JSON — cannot write entries to the Codex.");
  }
  const entries = (parsed as { entries?: unknown }).entries;
  if (!Array.isArray(entries)) {
    throw new Error(
      'Codex documentation artifact JSON must have a top-level "entries" array — see the codex_documentation Generator prompt contract in CLAUDE.md.'
    );
  }
  return { entries: entries as ParsedCodexDocumentationArtifact["entries"] };
}

// Writes an approved codex_documentation unit directly into codex_entries
// — unlike on-demand entity extraction (extractEntities/confirmEntities),
// which stays proposal-only elsewhere, this stage's whole job IS to
// produce the book's initial character/world documentation, so approving
// it commits the entries the same way approving a part_beats chunk
// commits its beats. Only the fields Layer 1 (rag.ts) and the human-
// facing Codex UI actually care about most for a fresh book — richer
// fields (background, life_events, etc.) stay writer-editable afterward
// through the normal Codex CRUD surface, same as any other entry.
async function materializeCodexDocumentation(bookId: string, userId: string, artifactJson: string): Promise<void> {
  const supabase = getSupabaseClient();
  const { entries } = parseCodexDocumentationArtifact(artifactJson);
  if (entries.length === 0) return;

  // Idempotency guard against a retry after a later failure in the same
  // approve call — same reasoning as materializeBeats's guard above. Skip
  // any entry that's already an exact (name, entryType) match for this
  // book rather than risk a duplicate Codex entry on a retried approve.
  const { data: existing, error: existingError } = await supabase
    .from("codex_entries")
    .select("name, entry_type")
    .eq("book_id", bookId);
  if (existingError) throw new Error(`Failed to check existing Codex entries: ${existingError.message}`);
  const existingKeys = new Set((existing ?? []).map((e) => `${e.name} ${e.entry_type}`));

  const rows = entries
    .filter((e) => !existingKeys.has(`${e.name} ${e.entryType}`))
    .map((e) => ({
      user_id: userId,
      book_id: bookId,
      name: e.name,
      entry_type: e.entryType || "character",
      description: e.description ?? "",
      aliases: e.aliases ?? null,
      tier: e.tier ?? null,
      personality_traits: e.personalityTraits ?? null,
      motivations: e.motivations ?? null,
    }));
  if (rows.length === 0) return;

  const { error } = await supabase.from("codex_entries").insert(rows);
  if (error) throw new Error(`Failed to write Codex documentation entries: ${error.message}`);
}

// Writer approves the unit at the human review gate. On part_outline, this
// records the Part's committed chapter range (part_chapter_ranges) for
// part_beats to use. On part_beats, this also materializes the chunk into
// the Outliner and reconciles the continuity ledger, before advancing.
// Approving the very last unit (Act 3 Part 3's last beats chunk) marks the
// whole run done — the book is fully planned.
export async function approveStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const unit = currentUnitKey(run);
  const pos = currentPosition(run);

  let partChapterRanges = run.part_chapter_ranges;
  let continuityLedger = run.continuity_ledger;

  if (pos.stage === "part_outline") {
    try {
      const { startChapter, endChapter } = parsePartOutlineArtifact(run.stage_artifacts[unit] ?? "{}");
      partChapterRanges = { ...run.part_chapter_ranges, [partRangeKey(pos.act as number, pos.part as number)]: { startChapter, endChapter } };
    } catch (error) {
      return markFailed(runId, error);
    }
  }

  if (pos.stage === "part_beats" || pos.stage === "hook_chapters_outline") {
    try {
      await materializeBeats(run.book_id, run.user_id, run.stage_artifacts[unit] ?? "{}");
      continuityLedger = await appendLedgerFacts(run, unit, run.stage_artifacts[unit] ?? "{}");
    } catch (error) {
      return markFailed(runId, error);
    }
  }

  if (pos.stage === "codex_documentation") {
    try {
      await materializeCodexDocumentation(run.book_id, run.user_id, run.stage_artifacts[unit] ?? "{}");
    } catch (error) {
      return markFailed(runId, error);
    }
  }

  // Snapshot this unit's critique before clearing it — advancing wipes
  // panel_reviews/arbitrator_synthesis for the new unit's own cycle, but
  // unapproveStage needs the just-approved unit's data back if the writer
  // meant to reject instead.
  const stagePanelHistory = {
    ...run.stage_panel_history,
    [unit]: { panel_reviews: run.panel_reviews, arbitrator_synthesis: run.arbitrator_synthesis },
  };

  const next = nextPosition(pos, partChapterRanges);

  if (!next) {
    return saveRun(runId, {
      status: "done",
      part_chapter_ranges: partChapterRanges,
      continuity_ledger: continuityLedger,
      stage_panel_history: stagePanelHistory,
    });
  }

  return saveRun(runId, {
    current_stage: next.stage,
    current_act: next.act,
    current_part: next.part,
    current_beat_chunk: next.beatChunk,
    status: "generating",
    panel_reviews: null,
    arbitrator_synthesis: null,
    part_chapter_ranges: partChapterRanges,
    continuity_ledger: continuityLedger,
    stage_panel_history: stagePanelHistory,
  });
}

// Writer rejects the artifact — opens the Arbitrator chat interview.
// Deliberately does NOT reset chat_history — the Arbitrator is meant to
// be one continuous point of contact for the whole run, not a fresh
// stranger every time a unit gets rejected. See chatTurn/finalizeDirective
// for how the accumulated history actually gets used.
export async function rejectStage(runId: string): Promise<PlanningRun> {
  return saveRun(runId, { status: "user_chat_active" });
}

// Writer approved a unit but changes their mind before doing anything on
// the next one — undoes that approval and reopens the PREVIOUS unit's
// rejection interview directly, so its own critique can actually be acted
// on instead of being stuck advanced past it. Goes straight to the
// interview (not back to the review gate) since the review gate's job —
// approve or reject — has already been answered. Restores that unit's
// panel_reviews/arbitrator_synthesis from stage_panel_history (see
// approveStage) rather than leaving them empty. Refuses if the current
// unit already has its own generated artifact — reverting would silently
// discard real generated content, the same non-destructive principle
// every other write path here follows.
export async function unapproveStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const pos = currentPosition(run);
  const prev = previousPosition(pos, run.part_chapter_ranges);
  if (!prev) {
    throw new Error("Already at the first unit — there is no previous unit to reopen.");
  }

  if (run.stage_artifacts[currentUnitKey(run)]) {
    throw new Error(
      "Cannot reopen the previous unit — the current unit already has a generated artifact, and reverting would discard it. Reject the current unit's own artifact instead if that's what needs changing."
    );
  }

  const restored = run.stage_panel_history[unitKey(prev)];

  return saveRun(runId, {
    current_stage: prev.stage,
    current_act: prev.act,
    current_part: prev.part,
    current_beat_chunk: prev.beatChunk,
    status: "user_chat_active",
    panel_reviews: restored?.panel_reviews ?? null,
    arbitrator_synthesis: restored?.arbitrator_synthesis ?? null,
  });
}

// Writer wants nothing to do with the current unit's draft — not even a
// revision via the interview, just gone. Falls back to the PREVIOUS
// unit's review gate (not its interview — there's nothing to discuss; the
// writer is just re-approving to trigger a genuinely fresh generation,
// not a revision of what they trashed). Unlike unapproveStage, this is
// allowed even when the current unit already has a generated artifact —
// discarding it is the entire point. Explicitly deletes
// stage_artifacts[unit] so the next generate call's {{PREVIOUS_ARTIFACT}}
// is genuinely empty, not a silent revision of the discarded draft.
export async function discardStage(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const pos = currentPosition(run);
  const prev = previousPosition(pos, run.part_chapter_ranges);
  if (!prev) {
    throw new Error("Already at the first unit — there is no previous unit to fall back to.");
  }
  const restored = run.stage_panel_history[unitKey(prev)];

  const stageArtifacts = { ...run.stage_artifacts };
  delete stageArtifacts[currentUnitKey(run)];

  return saveRun(runId, {
    current_stage: prev.stage,
    current_act: prev.act,
    current_part: prev.part,
    current_beat_chunk: prev.beatChunk,
    status: "awaiting_user_review",
    stage_artifacts: stageArtifacts,
    panel_reviews: restored?.panel_reviews ?? null,
    arbitrator_synthesis: restored?.arbitrator_synthesis ?? null,
  });
}

// One turn of the Arbitrator chat interview. Every prior turn is resent —
// the API is stateless per call, same as every LLM API, Hanami included;
// "memory" only ever exists because the caller resends history, exactly
// like the Chat Assistant and scene-draft-sessions already do elsewhere
// in this project.
//
// The Arbitrator is the writer's one continuous point of contact with the
// whole pipeline, not a fresh stranger at every rejection — so the
// history resent here is intake_chat_history + the ENTIRE accumulated
// chat_history across every unit/rejection cycle so far, not just the
// current one (chat_history is never reset — see rejectStage/
// unapproveStage/approveStage). Deliberate exception to the per-call-
// stays-cheap principle everywhere else in this pipeline: later-run
// interviews cost more per turn than earlier ones, since the full
// transcript grows for the life of the run.
export async function chatTurn(runId: string, userMessage: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const unit = currentUnitKey(run);
    const artifact = run.stage_artifacts[unit] ?? "";
    const prompt = await getActivePrompt(run.book_id, "arbitrator_chat", run.current_stage);

    const priorTurns: PlanningChatMessage[] = [...run.intake_chat_history, ...run.chat_history];

    const anthropic = getAnthropicClient();
    const contextPreamble = interpolateTemplate(prompt.user_prompt_template, {
      CURRENT_ARTIFACT: artifact,
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
    });

    const response = await anthropic.messages.create({
      model: prompt.model,
      max_tokens: 4096,
      system: prompt.system_prompt,
      thinking: { type: "adaptive" },
      output_config: { effort: prompt.effort },
      messages: [
        { role: "user", content: contextPreamble },
        ...priorTurns.map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: userMessage },
      ],
    });

    const reply = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();

    return saveRun(runId, {
      chat_history: [...run.chat_history, { role: "user", content: userMessage }, { role: "assistant", content: reply }],
    });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Compiles the chat interview into one crisp technical directive, then
// loops back to the Generator for this same unit (reject -> chat ->
// directive -> regenerate). {{CHAT_HISTORY}} is the full intake +
// accumulated interview history, same "one continuous Arbitrator" memory
// chatTurn uses — not just this cycle's turns. chat_history is never
// cleared here.
export async function finalizeDirective(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const unit = currentUnitKey(run);
    const prompt = await getActivePrompt(run.book_id, "arbitrator_directive", run.current_stage);
    const fullHistory: PlanningChatMessage[] = [...run.intake_chat_history, ...run.chat_history];
    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      CHAT_HISTORY: JSON.stringify(fullHistory, null, 2),
      PANEL_REVIEWS: JSON.stringify(run.panel_reviews ?? {}, null, 2),
      CURRENT_ARTIFACT: run.stage_artifacts[unit] ?? "",
    });

    const directive = await callAgent({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    return saveRun(runId, { status: "generating", final_delta_directive: directive });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// One turn of the pre-Stage-1 intake conversation — the writer describing
// in plain language what this book is, rather than filling out a form.
// Same Arbitrator role as the rejection interview, but a distinct prompt
// (looked up at stage 'intake') and a separate chat thread
// (intake_chat_history), since it's a different moment with a different
// job. Gives Claude the server-side web_fetch tool so pasting a reference
// link actually gets read, not just acknowledged — Anthropic fetches and
// reads the page itself within this same call, no scraping code needed
// here. Also accepts an optional inline document (base64) for "upload a
// doc" — read once to inform the brief, never persisted, so this doesn't
// need the Storage-bucket setup a permanent asset (like a character
// portrait) would.
export async function intakeChatTurn(
  runId: string,
  userMessage: string,
  document?: { base64: string; mediaType: string }
): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "arbitrator_chat", "intake");
    const bookContext = await buildBookContext(run.book_id);
    const history: PlanningChatMessage[] = [...run.intake_chat_history, { role: "user", content: userMessage }];

    const anthropic = getAnthropicClient();
    const contextPreamble = interpolateTemplate(prompt.user_prompt_template, { BOOK_CONTEXT: bookContext });

    const userContent: Anthropic.MessageParam["content"] = document
      ? [
          { type: "document", source: { type: "base64", media_type: document.mediaType as "application/pdf", data: document.base64 } },
          { type: "text", text: userMessage },
        ]
      : userMessage;

    const response = await anthropic.messages.create({
      model: prompt.model,
      max_tokens: 4096,
      system: prompt.system_prompt,
      thinking: { type: "adaptive" },
      output_config: { effort: prompt.effort },
      // Server-side tool — Anthropic fetches and reads the page itself
      // within this same call, no client-side execution loop needed. Not
      // in the SDK's plain Tool type (that's for custom tools with an
      // input_schema), hence the through-unknown cast.
      tools: [{ type: "web_fetch_20260209", name: "web_fetch", max_uses: 5 } as unknown as Anthropic.Tool],
      messages: [
        { role: "user", content: contextPreamble },
        ...history.slice(0, -1).map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: userContent },
      ],
    });

    const reply = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();

    return saveRun(runId, { intake_chat_history: [...history, { role: "assistant", content: reply }] });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// Compiles the intake conversation into the Generator's first real input
// (final_delta_directive — same field a rejection's directive uses; the
// Generator doesn't need to know whether direction came from an initial
// brief or a correction, only that it exists) and opens up Stage 1.
export async function finalizeIntake(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "arbitrator_directive", "intake");
    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      CHAT_HISTORY: JSON.stringify(run.intake_chat_history, null, 2),
    });

    const directive = await callAgent({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    return saveRun(runId, { status: "generating", final_delta_directive: directive });
  } catch (error) {
    return markFailed(runId, error);
  }
}

// On-demand, not automatic — a real behavior change from the old flat
// model, where entity extraction auto-fired once after the whole book's
// beats were approved. Under the Act/Part hierarchy a Part can be
// approved months before the next one, so tying extraction (and its
// review-gate status) to every single beats-chunk approval would mean a
// forced review screen after every one of up to 9+ chunks. Instead this
// is a plain callable action the writer triggers whenever they want —
// scans every approved part_beats chunk so far. Deliberately does not use
// markFailed or touch `status`: this is a side action, not the main
// pipeline position, and an error here must not make the run look like
// its actual pipeline step failed.
export async function extractEntities(runId: string): Promise<PlanningRun> {
  const run = await loadRun(runId);
  try {
    const prompt = await getActivePrompt(run.book_id, "entity_extractor", "all");
    const bookContext = await buildBookContext(run.book_id);
    const beatsArtifacts = Object.entries(run.stage_artifacts)
      .filter(([key]) => key.includes("_beats_chunk_"))
      .map(([, value]) => value)
      .join("\n\n");

    const userMessage = interpolateTemplate(prompt.user_prompt_template, {
      BOOK_CONTEXT: bookContext,
      CURRENT_ARTIFACT: beatsArtifacts,
    });

    const raw = await callAgentForJson({
      systemPrompt: prompt.system_prompt,
      userMessage,
      model: prompt.model,
      effort: prompt.effort,
    });

    const candidates = Array.isArray(raw) ? (raw as ExtractedEntityCandidate[]) : [];
    return saveRun(runId, { extracted_entities: candidates });
  } catch (error) {
    console.error("extract entities failed:", error);
    throw error instanceof Error ? error : new Error(String(error));
  }
}

// Writer's batch review of extracted entities: writes only the approved
// indexes into the real codex_entries/world_categories tables, via the
// same tables (not a parallel copy) the rest of the product already reads
// and writes. Does not touch `status` — extraction/confirmation is a side
// action independent of the run's actual pipeline position (see
// extractEntities), not something that marks a whole run "done".
export async function confirmEntities(runId: string, approvedIndexes: number[]): Promise<PlanningRun> {
  const run = await loadRun(runId);
  const supabase = getSupabaseClient();
  const candidates = run.extracted_entities ?? [];

  for (const index of approvedIndexes) {
    const candidate = candidates[index];
    if (!candidate) continue;

    if (candidate.type === "codex_entry") {
      const { error } = await supabase.from("codex_entries").insert({
        user_id: run.user_id,
        book_id: run.book_id,
        name: candidate.name,
        entry_type: candidate.entryType ?? "character",
        description: candidate.description ?? "",
      });
      if (error) throw new Error(`Failed to create Codex entry "${candidate.name}": ${error.message}`);
    } else if (candidate.type === "world_category") {
      const { error } = await supabase.from("world_categories").insert({
        book_id: run.book_id,
        key: candidate.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
        name: candidate.name,
        description: candidate.description ?? null,
      });
      if (error && error.code !== "23505") throw new Error(`Failed to create world category "${candidate.name}": ${error.message}`);
    }
  }

  return saveRun(runId, { extracted_entities: null });
}
